trigger:
- master
- dev/*

pr:
- master

variables:
- group: noos_releases_group_variables
- name: isMain
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
- job: Projects
  pool: LocalPool
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: true
    clean: true
    persistCredentials: true
  - script: 'python ./tools/scripts/build_projects.py . $(RELEASE_DIR)'
    displayName: 'Run project build'
  - task: PublishPipelineArtifact@1
    condition: eq(variables.isMain, true)
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/$(RELEASE_DIR)'
      artifact: '$(ARTIFACT_NAME)'
      publishLocation: 'pipeline'